### ISSUE TITLE
Raspberry Pi 4: Type object 'str' has no attribute 'fromhex'

### ISSUE THREAD

**Issue by adwinang** [HuskyLens/HUSKYLENSPython#1]
`Traceback (most recent call last):
  File "adwin.py", line 4, in <module>
    print(my_Var.command_request_knock())
  File "/home/pi/Desktop/HuskyLens/HUSKYLENSPython/HUSKYLENS/huskylensPythonLibrary.py", line 178, in command_request_knock
    cmd = self.cmdToBytes(commandHeaderAndAddress+"002c3c")
  File "/home/pi/Desktop/HuskyLens/HUSKYLENSPython/HUSKYLENS/huskylensPythonLibrary.py", line 107, in cmdToBytes
    return bytes.fromhex(cmd)
AttributeError: type object 'str' has no attribute 'fromhex'
`
I encountered this problem when I was running the test.py file.

**Comment by adwinang** [comment]
ignore the File "adwin.py", copied pasted the wrong error message, but I encountered the same problem for the test.py

**Comment by robertprast** [comment]
Could you let me know which versions of Python you are using ? 

The .fromhex() was added to added to Pythons standard library in versions 3.5. Therefore, please use Python 3.5 or higher. 

To check your versions of python you can simply run:
```python3 --version``` or ```python --version```

**Comment by adwinang** [comment]
Hi, I realised my mistake, I thought I was using python3. But I was using python2 

I encountered another problem which is 
`Traceback (most recent call last):
  File "test.py", line 28, in <module>
    print(test.command_request())
  File "/home/pi/Desktop/HuskyLens/HUSKYLENS/huskylensPythonLibrary.py", line 187, in command_request
    self.writeToHuskyLens(cmd)
  File "/home/pi/Desktop/HuskyLens/HUSKYLENS/huskylensPythonLibrary.py", line 97, in writeToHuskyLens
    self.huskylensSer.write_i2c_block_data(self.address,12, list(cmd))
OSError: [Errno 121] Remote I/O error
`
I have used the i2cdetect command to check whether I'm using the correct address, which I was.
