### ISSUE TITLE
TypeError: int() can't convert non-string with explicit base

### ISSUE THREAD

**Issue by santooooooo** [HuskyLens/HUSKYLENSPython#7]
I use HuskyLens with Raspberry Pi 3B+ and Python 3.7.3.
I wanted to use `learn` function so wrote code.
Here is the code.

  ```python
 from huskylib import HuskyLensLibrary
  import time
  
  my_Var = HuskyLensLibrary("I2C","", address=0x32)
  
  def changeMode():
       my_Var.algorthim("ALGORITHM_FACE_RECOGNITION")
  
 def output():
     block = my_Var.requestAll()
      for i in block:
          print(i.ID)
          print(i.learned)
 
  changeMode()
  time.sleep(3)
  my_Var.learn(1)
  output()
```

When I ran it, some errors occurred.
Here is the errors.

```
Traceback (most recent call last):
  File "/home/pi/Python/HUSKYLENSPython/HUSKYLENS/huskylib.py", line 179, in processReturnData
    commandSplit[4][2:4]+commandSplit[4][0:2], 16)
TypeError: int() can't convert non-string with explicit base

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "learn.py", line 20, in <module>
    my_Var.learn(1)
  File "/home/pi/Python/HUSKYLENSPython/HUSKYLENS/huskylib.py", line 253, in learn
    return self.processReturnData()
  File "/home/pi/Python/HUSKYLENSPython/HUSKYLENS/huskylib.py", line 217, in processReturnData
    self.huskylensSer.timeout=5
AttributeError: 'SMBus' object has no attribute 'timeout'
```
Please tell me why the errors occurred and how to use `learn` function.

**Comment by suarez-ramon** [comment]
Hello, @santooooooo did you solve this problem?

**Comment by santooooooo** [comment]
Hi, @suarez-ramon .
Sorry to react your comment late.
I couldn't solve this problem but I don't mind about it because I don't use HuskyLens now.
So I close this issue.
